language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_install:
  - sudo apt-get update
  - sudo apt-get install libusb-1.0-0 libusb-1.0-0-dev

script:
  - cargo build
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then cargo test --features web; else cargo test; fi
