[package]
name = "archiver"
version = "0.1.0"
authors = ["Richo Healey <richo@psych0tik.net>"]

[features]
"web" = [
  "rocket",
  "rocket_codegen",
  "rocket_contrib",
]

[dependencies]
toml = "0.4.6"
clap = "2.32.0"
serde = "1.0.76"
serde_derive = "1.0.71"
serde_json = "1.0.26"
failure = "0.1.2"
lazy_static = "1.1.0"
libusb = "0.3.0"
ptp = { "git" = "https://github.com/richo/rust-ptp" }
chrono = { version = "0.4", features = ["serde"] }
regex = "1.0.2"
reqwest = "0.8.8"
hyper = "0.11.27"
log = "0.4.4"
pretty_env_logger = "0.2.4"
hashing-copy = "0.1"
tempfile = "3.0.3"
walkdir = "2.2.5"
hex = "0.3"
digest = "0.7"
sha2 = "0.7"
handlebars = "1.0.3"
sendgrid = { "git" = "https://github.com/gsquire/sendgrid-rs" }

rocket = { git = "https://github.com/SergioBenitez/Rocket", optional = true }
rocket_codegen = { git = "https://github.com/SergioBenitez/Rocket", optional = true }
rocket_contrib = { git = "https://github.com/SergioBenitez/Rocket", optional = true, default-features = false, features = ["handlebars_templates", "json", "static_files"] }

[[bin]]
name = "server"
path = "src/bin/server.rs"
required-features = ["web"]

[[bin]]
name = "runner"
path = "src/bin/runner.rs"
