[package]
name = "archiver"
version = "0.1.0"
authors = ["Richo Healey <richo@psych0tik.net>"]

[dependencies]
toml = "0.4.6"
clap = "2.32.0"
serde = "1.0.71"
serde_derive = "1.0.71"
serde_json = "1.0.26"
failure = "0.1.2"
lazy_static = "1.1.0"
libusb = "0.3.0"
ptp = "0.5.0"
chrono = "0.4.5"
regex = "1.0.2"
reqwest = "0.8.8"
hyper = "0.11.27"
