version: "3"
services:
  web:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - target:/app/target
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - /var/lib/postgresql/data

volumes:
  target: {}
