version: "3"
services:
  web:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - target:/app/target
    depends_on:
      - db
    environment:
      ROCKET_ADDRESS: 0.0.0.0
      DATABASE_URL: postgres://archiver:archiver@db/archiver_web

  db:
    image: postgres
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: archiver
      POSTGRES_PASSWORD: archiver

volumes:
  target: {}
