# Configuration for archiver.
# Comment out any section to disable that feature.

[archiver]

storage_backend="dropbox"

[dropbox]
token="DROPBOX_TOKEN_GOES_HERE"

[[flysight]]
name = "data"
mountpoint = "test-data/flysight"

[[mass_storage]]
name = "video"
mountpoint="test-data/mass_storage"
extensions=["mp4"]

[[mass_storage]]
name = "dummy"
mountpoint="test-data/nonexistant"
extensions=["ogv"]
